### ISSUE TITLE
MiaSample incorrectly includes checkout cancelUrl when performing embedded checkout

### ISSUE THREAD

**Issue by ctsrc** [Nets-eCom/Nets-Easy-iOS-SDK#11]
Changing the settings from the swipe-out settings menu from "HostedPaymentPage" to "EmbeddedCheckout", and attempting checkout results in the following error:

```text
400 'https://test.api.dibspayment.eu/v1/payments' [0.3617 s]:
```

```text
[...]
```

```text
{
  "errors" : {
    "checkout.CancelUrl" : [
      "Cancel url is only supported for hosted checkout"
    ]
  }
}
```

The fix for it is a simple one, which I'm submitting as a pull request that will reference this issue.

**Comment by Nets-in-app** [comment]
Hi @ctsrc ,

Thanks for your suggestion! As the latest release, we decided to remove EmbeddedCheckout from Sample App and promote the HostedPaymentPage as preferable integration mode for mobile in-App integration. Anyway, thanks for providing the good suggestion and its fix PR for us!
