### ISSUE TITLE
 Undefined symbol: _OBJC_CLASS_$_MiaSDK

### ISSUE THREAD

**Issue by Maddumage** [Nets-eCom/Nets-Easy-iOS-SDK#18]
I have downloaded the latest version (1.5.0) and integrated it with my react-native application. The android platform configuration was a success, but for iOS I got this error when running the project.
"react-native": "0.64.2",
iPhone 13 Pro Emulator in Xcode - 13

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_MiaSDK", referenced from:
      objc-class-ref in libreact-native-rn-mia.a(RnMia.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Nets-in-app** [comment]
Hello @Maddumage,

Thank you for reaching out to us. As you mentioned you are using version 1.2.0, I would recommend you to use the latest SDK version (v1.5.0) and check if you still face the issue. In the mean we will at our end as well.

Best regards

**Comment by Maddumage** [comment]
@Nets-in-app Hi, I am very sorry, I have mentioned the wrong version number. I have downloaded and used the latest one (v1.5.0).
Also updated the comment above.

**Comment by Nets-in-app** [comment]
Hi, are you using the xcframework ?

**Comment by Nets-in-app** [comment]
@Maddumage  Please try with the provided xcframework

**Comment by Maddumage** [comment]
@Nets-in-app @barteljan 
Thank you, I will check with the suggested workaround.
