### ISSUE TITLE
Dependency "Easy-iOS-SDK" has no shared framework schemes: Failed to Import Mia 

### ISSUE THREAD

**Issue by prasid444** [Nets-eCom/Nets-Easy-iOS-SDK#3]
**OUTPUT** of `carthage update`

*** Cloning Easy-iOS-SDK
*** Checking out Easy-iOS-SDK at "1.2.0"
*** xcodebuild output can be found in /var/folders/5t/5fg5s4b94tn0jrxyhj95nvx00000gn/T/carthage-xcodebuild.yi0via.log
*** Skipped building Easy-iOS-SDK due to the error:
Dependency "Easy-iOS-SDK" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/DIBS-Payment-Services/Easy-iOS-SDK/issues/new

**Cartfile**
github "DIBS-Payment-Services/Easy-iOS-SDK"

**Comment by Nets-in-app** [comment]
Hi @prasid444 ,

Is it still valid issue in the latest version?

**Comment by Nets-in-app** [comment]
Hi,
No update for this issue. Hence closing, in case of doubt please re-open the issue.

Thanks,
