### ISSUE TITLE
React Native: Checkout window doesn't work on IOS

### ISSUE THREAD

**Issue by krini** [Nets-eCom/Nets-Easy-iOS-SDK#38]
I have created a new react native app and installed this package:
`"react-native-rn-mia": "^1.6.1"`

I use these versions
```
"react": "18.2.0",
"react-native": "0.72.6",
```

I have manually added Mia.xcframework to Frameworks in xcode.

When I call RNMia.checkoutWithPaymentID I get a window looking like this:
![image](https://github.com/Nets-eCom/Nets-Easy-iOS-SDK/assets/10484265/e30460af-a895-4ccc-b525-68ab9fb1631c)

The app is found here:
https://github.com/krini/nets-checkout

**Comment by BuildManager-Nets** [comment]
Hi @krini ,

Sorry to get back to you late!  From your RN app, I can see that you provide the wrong checkout URL 'https://test.checkout.dibspayment.eu/v1/checkout.js?v=1',.
"
presentMiaCheckout(
              '0223000065423058f20277be481580c5',
              'https://test.checkout.dibspayment.eu/v1/checkout.js?v=1',
            );"

Please follow the instruction from Easy payment API to get hostedpaymentpageurl and provide it here to replace wrong url and you can find the description of API here https://developer.nexigroup.com/nexi-checkout/en-EU/api/payment-v1/#v1-payments-post-responses-201-hostedpaymentpageurl.

**Comment by Miss-PiA** [comment]
Hi @krini .

Nice to hear that the issue gets solved! Let us know if you have any further questions.
